import assert from 'node:assert/strict';
import {act,seed,empty,remaining,filterDebts,defaults,minor,today,validate} from '../lib/model.ts';
let s=seed();
assert.equal(remaining(s,s.debts.find(d=>d.id==='d2')!),4500000);
assert.equal(s.transactions.filter(t=>t.debtId==='d2').length,2);
const original=structuredClone(s.debts);
s=act(s,{type:'setoff',personId:'p0',currency:'USD',date:today()});
assert.equal(remaining(s,s.debts.find(d=>d.id==='d0')!),2000000);
assert.equal(remaining(s,s.debts.find(d=>d.id==='d1')!),0);
assert.deepEqual(s.debts,original);
assert.throws(()=>act(s,{type:'setoff',personId:'p0',currency:'USDT'}));
assert.throws(()=>act(s,{type:'return',id:'d0',amount:'20001'}));
assert.throws(()=>act(s,{type:'return',id:'d0',amount:'-1'}));
assert.throws(()=>act(s,{type:'return',id:'d0',amount:'5',date:'2020-01-01'}));
s=act(s,{type:'return',id:'d0',amount:'0.01',date:today(),comment:'Копейка'});
assert.equal(remaining(s,s.debts.find(d=>d.id==='d0')!),1999999);
const oldDue=s.debts.find(d=>d.id==='d0')!.due;
s=act(s,{type:'due',id:'d0',due:'2027-01-20'});
assert.ok(s.notes.at(-1)!.text.includes(oldDue));
s=act(s,{type:'note',id:'d0',text:'Уникальный комментарий про таможню',date:today()});
assert.equal(filterDebts(s,{...defaults,search:'Уникальный комментарий'}).length,1);
assert.equal(filterDebts(s,{...defaults,direction:'in',currency:'USDT',timing:'overdue'}).length,1);
assert.equal(filterDebts(s,{...defaults,search:'2 000 000'}).length,1);
assert.deepEqual(act(empty(),{type:'restore',data:JSON.parse(JSON.stringify(s))}),s);
const bad=structuredClone(s);bad.transactions[0].amount=999999999;assert.throws(()=>validate(bad));
assert.equal(minor('1 234,56'),123456);assert.throws(()=>minor('0.001'));assert.throws(()=>minor('0'));
s=act(s,{type:'debt',personName:'Тест',direction:'in',amount:'300000',currency:'KZT',date:today(),due:'',purpose:'Аванс',comment:'Длинные подробности',categoryId:'cat0',tags:['наличные'],reminderDays:[]});
assert.ok(s.people.some(p=>p.name==='Тест'));assert.equal(filterDebts(s,{...defaults,search:'300000',currency:'KZT'}).length,1);
console.log('PASS: partial repayments, cent precision, overpayment rejection, date validation, same-currency offsets, original history, due changes, search, combined filters, backup integrity, fast person creation');
