import assert from 'node:assert/strict';
import { selectPerson, editPersonInput } from '../lib/person-selection.ts';
import { receiptData, wrapReceiptText } from '../lib/receipt.ts';
import { seed } from '../lib/model.ts';
const p = { id: 'p0', name: 'Магомед' };
const quick = selectPerson(p);
let dropdown = selectPerson(p);
dropdown = editPersonInput(dropdown, p.name, 'item-press');
dropdown = editPersonInput(dropdown, '', 'none');
assert.deepEqual(dropdown, quick);
assert.deepEqual(editPersonInput(dropdown, 'Аслан', 'input-change'), { id: '', name: 'Аслан' });
assert.deepEqual(editPersonInput(dropdown, '', 'input-change'), { id: '', name: '' });
const draft = { id: '', name: 'Новый человек' };
assert.deepEqual(editPersonInput(draft, '', 'input-clear'), draft);
const s = seed(); const date = '2026-09-12T14:00:00Z';
const partial = receiptData(s, s.debts.find(d => d.id === 'd2')!, date);
assert.equal(partial.principal, '$100\u00a0000');
assert.equal(partial.returned, '$55\u00a0000');
assert.equal(partial.balance, '$45\u00a0000');
assert.equal(partial.createdAt, s.debts.find(d => d.id === 'd2')!.createdAt);
assert.match(partial.direction, /Аслан должен автору записи/);
const offset = receiptData(s, s.debts.find(d => d.id === 'd0')!, date);
assert.equal(offset.offset, '$10\u00a0000');
assert.equal(offset.returned, '$0');
assert.equal(offset.balance, '$40\u00a0000');
assert.match(offset.direction, /Автор записи должен: Магомед/);
assert.equal(receiptData(s, s.debts.find(d => d.id === 'd5')!, date).balance, '0 ₽');
for (const text of ['Очень длинный комментарий '.repeat(1000), 'Д'.repeat(500), 'Первая строка\n\nВторая строка']) {
  const lines = wrapReceiptText(text, 30, s => Array.from(s).length);
  assert.ok(lines.every(line => Array.from(line).length <= 30));
  assert.equal(lines.join('').replace(/\s/g, ''), text.replace(/\s/g, ''));
}
console.log('PASS: dropdown/quick-contact parity, no selection reset on library callbacks, typing/clearing, full receipt totals and directions, long text without clipping');
