import { z } from 'zod';
export const currencies=['RUB','USD','USDT','CNY','EUR','KZT'] as const;
export const symbols:Record<string,string>={RUB:'₽',USD:'$',USDT:'₮',CNY:'¥',EUR:'€',KZT:'₸'};
export const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Moscow'});
export const uid=()=>crypto.randomUUID();
const id=z.string().min(1).max(100), text=z.string().max(20000), date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Некорректная дата');
const money=z.number().int().positive().max(9000000000000);
export const personSchema=z.object({id,name:z.string().trim().min(1).max(120)});
export const debtSchema=z.object({id,personId:id,direction:z.enum(['in','out']),amount:money,currency:z.enum(currencies),date,due:z.union([date,z.literal('')]),purpose:z.string().max(250),comment:text,categoryId:id,tags:z.array(z.string().trim().min(1).max(80)).max(30),createdAt:z.string()});
const txSchema=z.object({id,debtId:id,amount:money,kind:z.enum(['return','setoff']),date,comment:text,groupId:id,createdAt:z.string()});
const noteSchema=z.object({id,debtId:z.string(),personId:id,kind:z.enum(['note','due','edit']),text,date,createdAt:z.string()});
export const stateSchema=z.object({people:z.array(personSchema).max(2000),debts:z.array(debtSchema).max(5000),transactions:z.array(txSchema).max(20000),notes:z.array(noteSchema).max(20000),categories:z.array(z.object({id,name:z.string().trim().min(1).max(80)})).min(1).max(100),reminders:z.array(z.object({id,debtId:id,days:z.number().int().min(-1).max(7)})).max(25000),filters:z.array(z.object({id,name:z.string().min(1).max(80),value:z.record(z.string())})).max(100)});
export type State=z.infer<typeof stateSchema>;export type Debt=z.infer<typeof debtSchema>;
export const empty=():State=>({people:[],debts:[],transactions:[],notes:[],categories:['Авто','Бизнес','Личное','Семья','Партнерство','Другое'].map((name,i)=>({id:'cat'+i,name})),reminders:[],filters:[]});
export const remaining=(s:State,d:Debt)=>d.amount-s.transactions.filter(t=>t.debtId===d.id).reduce((v,t)=>v+t.amount,0);
export const amountText=(a:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(a/100);
export const fmt=(a:number,c:string)=>c==='USD'?'$'+amountText(a):c==='EUR'?'€'+amountText(a):amountText(a)+' '+(c==='USDT'?'USDT':symbols[c]);
export function minor(v:unknown){const t=String(v).replace(/[\s\u00a0]/g,'').replace(',','.');if(!/^\d{1,11}(\.\d{1,2})?$/.test(t))throw Error('Введите корректную сумму (не более 2 знаков после запятой)');return money.parse(Math.round(Number(t)*100));}
export function validate(s:State){stateSchema.parse(s);for(const list of [s.people,s.debts,s.transactions,s.notes,s.categories,s.reminders,s.filters])if(new Set(list.map(v=>v.id)).size!==list.length)throw Error('Повторяющиеся идентификаторы');for(const d of s.debts){if(!s.people.some(p=>p.id===d.personId)||!s.categories.some(c=>c.id===d.categoryId)||remaining(s,d)<0)throw Error('Нарушены связи или остаток долга');}for(const t of s.transactions)if(!s.debts.some(d=>d.id===t.debtId&&t.date>=d.date))throw Error('Некорректный возврат');for(const n of s.notes)if(!s.people.some(p=>p.id===n.personId)||n.debtId&&!s.debts.some(d=>d.id===n.debtId&&d.personId===n.personId))throw Error('Некорректная заметка');for(const r of s.reminders)if(!s.debts.some(d=>d.id===r.debtId))throw Error('Некорректное напоминание');for(const group of new Set(s.transactions.filter(t=>t.kind==='setoff').map(t=>t.groupId))){const ts=s.transactions.filter(t=>t.groupId===group);const ds=ts.map(t=>s.debts.find(d=>d.id===t.debtId)!);if(new Set(ds.map(d=>d.currency)).size!==1||new Set(ds.map(d=>d.personId)).size!==1||ts.reduce((v,t,i)=>v+(ds[i].direction==='in'?t.amount:-t.amount),0)!==0)throw Error('Некорректный взаимозачет');}return s;}
export function act(original:State,a:any):State{let s=structuredClone(original);const now=new Date().toISOString();const addTx=(d:Debt,n:number,kind:'return'|'setoff',groupId:string)=>{if(n>remaining(s,d))throw Error('Сумма превышает остаток');const dt=date.parse(a.date||today());if(dt<d.date)throw Error('Возврат не может быть раньше долга');s.transactions.push({id:uid(),debtId:d.id,amount:n,kind,date:dt,comment:text.parse(a.comment||''),groupId,createdAt:now});};
if(a.type==='person'){const p=personSchema.parse({id:uid(),name:a.name});if(s.people.some(x=>x.name.toLocaleLowerCase()===p.name.toLocaleLowerCase()))throw Error('Человек с таким именем уже есть');s.people.push(p);}
else if(a.type==='debt'){let personId=a.personId;if(!personId&&a.personName?.trim()){const p=personSchema.parse({id:uid(),name:a.personName});const existing=s.people.find(x=>x.name.toLocaleLowerCase()===p.name.toLocaleLowerCase());if(existing)personId=existing.id;else{s.people.push(p);personId=p.id;}}const d=debtSchema.parse({...a,id:uid(),personId,amount:minor(a.amount),createdAt:now});s.debts.push(d);for(const days of a.reminderDays||[])s.reminders.push({id:uid(),debtId:d.id,days});}
else if(a.type==='return'||a.type==='close'){const d=s.debts.find(d=>d.id===a.id);if(!d)throw Error('Долг не найден');addTx(d,a.type==='close'?money.parse(remaining(s,d)):minor(a.amount),'return',uid());}
else if(a.type==='setoff'){const ds=s.debts.filter(d=>d.personId===a.personId&&d.currency===a.currency&&remaining(s,d)>0).sort((x,y)=>x.date.localeCompare(y.date));const totals=['in','out'].map(dir=>ds.filter(d=>d.direction===dir).reduce((v,d)=>v+remaining(s,d),0));const n=Math.min(...totals);if(n<=0)throw Error('Нет встречных долгов в этой валюте');const group=uid();for(const dir of ['in','out']){let left=n;for(const d of ds.filter(d=>d.direction===dir)){const part=Math.min(left,remaining(s,d));if(part>0)addTx(d,part,'setoff',group);left-=part;}}}
else if(a.type==='note'||a.type==='due'||a.type==='edit'){const d=s.debts.find(d=>d.id===a.id);if(!d&&a.type!=='note')throw Error('Долг не найден');let value=text.parse(a.text||'').trim();if(a.type==='due'){const due=z.union([date,z.literal('')]).parse(a.due);value=`Срок перенесен с ${d!.due||'без срока'} на ${due||'без срока'}`;d!.due=due;}if(a.type==='edit'){value=`Изменены назначение и подробности. Ранее: ${d!.purpose}. ${d!.comment}`;d!.purpose=z.string().max(250).parse(a.purpose);d!.comment=text.parse(a.comment);}if(!value)throw Error('Добавьте текст заметки');s.notes.push({id:uid(),debtId:d?.id||'',personId:d?.personId||a.personId,kind:a.type,text:value,date:date.parse(a.date||today()),createdAt:now});}
else if(a.type==='deleteDebt'){
const debtId=id.parse(a.id);if(!s.debts.some(d=>d.id===debtId))throw Error('Запись уже удалена. Обновите список долгов.');
// A setoff is one balanced operation. Undo its entire group when removing a participant.
const groups=new Set(s.transactions.filter(t=>t.debtId===debtId&&t.kind==='setoff').map(t=>t.groupId));
s.transactions=s.transactions.filter(t=>t.debtId!==debtId&&!(t.kind==='setoff'&&groups.has(t.groupId)));
s.notes=s.notes.filter(n=>n.debtId!==debtId);s.reminders=s.reminders.filter(r=>r.debtId!==debtId);s.debts=s.debts.filter(d=>d.id!==debtId);
}
else if(a.type==='category'){const name=z.string().trim().min(1).max(80).parse(a.name);const c=s.categories.find(c=>c.id===a.id);if(c)c.name=name;else s.categories.push({id:uid(),name});}
else if(a.type==='deleteCategory'){if(s.debts.some(d=>d.categoryId===a.id))throw Error('Категория используется в долгах');s.categories=s.categories.filter(c=>c.id!==a.id);}
else if(a.type==='filter'){s.filters.push({id:uid(),name:a.name,value:a.value});}
else if(a.type==='deleteFilter'){s.filters=s.filters.filter(f=>f.id!==a.id);}
else if(a.type==='restore'){s=stateSchema.parse(a.data);}
else if(a.type==='seed'){if(s.debts.length||s.people.length)throw Error('Примеры можно добавить только в пустой учет');s=seed();}
else if(a.type==='clear'){s=empty();}
else throw Error('Неизвестное действие');return validate(s);}
export function seed():State{const s=empty(),now=new Date().toISOString();s.people=['Магомед','Аслан','Рустам','Тимур'].map((name,i)=>({id:'p'+i,name}));const offset=(days:number)=>{const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};const rows:any[]=[['p0','out',50000,'USD','Доплата за G63',12],['p0','in',30000,'USD','Аванс за автомобиль',8],['p1','in',100000,'USD','Покупка авто',15],['p2','in',25000,'USDT','Zeekr / таможня',-4],['p1','out',2000000,'RUB','Оборотные средства',0],['p3','in',150000,'RUB','Личное',-10]];s.debts=rows.map((r,i)=>({id:'d'+i,personId:r[0],direction:r[1],amount:r[2]*100,currency:r[3],purpose:r[4],date:offset(-25),due:r[5]?offset(r[5]):'',comment:i===0?'Взял у Магомеда $50,000 на доплату за G63. Договорились вернуть после продажи автомобиля.':'Демонстрационная запись — можно удалить в настройках.',categoryId:i<4?'cat0':'cat2',tags:i<4?['авто',i===3?'Zeekr':'G63']:['личное'],createdAt:now}));const tx=(debtId:string,n:number,kind:'return'|'setoff',days:number,groupId:string)=>({id:uid(),debtId,amount:n*100,kind,date:offset(days),comment:kind==='return'?'Частичный возврат':'Взаимозачет по договоренности',groupId,createdAt:now});s.transactions=[tx('d2',20000,'return',-15,uid()),tx('d2',35000,'return',-7,uid()),tx('d0',10000,'setoff',-3,'offset-demo'),tx('d1',10000,'setoff',-3,'offset-demo'),tx('d5',150000,'return',-12,uid())];s.reminders=[{id:uid(),debtId:'d3',days:-1},{id:uid(),debtId:'d0',days:7}];return validate(s);}
export const defaults={search:'',direction:'',status:'',timing:'',currency:'',category:'',person:'',tag:'',from:'',to:'',dueFrom:'',dueTo:'',group:'',sort:'new'};
export function filterDebts(s:State,f:Record<string,string>){return s.debts.filter(d=>{const r=remaining(s,d),p=s.people.find(p=>p.id===d.personId),c=s.categories.find(c=>c.id===d.categoryId);const q=f.search.toLowerCase().trim();const hay=[p?.name,d.amount/100,r/100,d.currency,symbols[d.currency],d.purpose,d.comment,c?.name,...d.tags,...s.notes.filter(n=>n.debtId===d.id).map(n=>n.text),...s.transactions.filter(t=>t.debtId===d.id).map(t=>t.comment)].join(' ').toLowerCase();const match=!q||hay.includes(q)||(/^\d[\d\s,.]*$/.test(q)&&[d.amount/100,r/100].some(v=>String(v)===q.replace(/\s/g,'').replace(',','.')));return match&&(!f.direction||d.direction===f.direction)&&(!f.currency||d.currency===f.currency)&&(!f.status||(f.status==='active'?r>0:r===0))&&(!f.timing||(f.timing==='overdue'?r>0&&!!d.due&&d.due<today():!d.due))&&(!f.category||d.categoryId===f.category)&&(!f.person||d.personId===f.person)&&(!f.tag||d.tags.includes(f.tag))&&(!f.from||d.date>=f.from)&&(!f.to||d.date<=f.to)&&(!f.dueFrom||!!d.due&&d.due>=f.dueFrom)&&(!f.dueTo||!!d.due&&d.due<=f.dueTo);}).sort((a,b)=>f.sort==='old'?a.createdAt.localeCompare(b.createdAt):f.sort==='name'?(s.people.find(p=>p.id===a.personId)?.name||'').localeCompare(s.people.find(p=>p.id===b.personId)?.name||'','ru'):f.sort==='amount'?a.currency.localeCompare(b.currency)||remaining(s,b)-remaining(s,a):f.sort==='due'?(a.due||'9999').localeCompare(b.due||'9999'):f.sort==='overdue'?Number(!!b.due&&b.due<today()&&remaining(s,b)>0)-Number(!!a.due&&a.due<today()&&remaining(s,a)>0):b.createdAt.localeCompare(a.createdAt));}
