import { env } from 'cloudflare:workers';
import { empty,State,validate,uid } from './model';
export function db(){if(!env.DB)throw Error('База данных временно недоступна');return env.DB;}
const tables=['people','categories','debts','transactions','notes','tags','debt_tags','reminders','saved_filters'];
const camel=(v:string)=>v.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());
const snake=(v:string)=>v.replace(/[A-Z]/g,c=>'_'+c.toLowerCase());
export async function read(user:string){const results=await db().batch([db().prepare('SELECT * FROM users WHERE id=?').bind(user),...tables.map(t=>db().prepare(`SELECT * FROM ${t} WHERE user_id=?`).bind(user))]);const u=results[0].results[0] as any;if(!u)throw Error('Пользователь не найден');const all:any={};tables.forEach((t,i)=>all[t]=results[i+1].results.map((r:any)=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='user_id').map(([k,v])=>[camel(k),v]))));const s:State={people:all.people,categories:all.categories.length?all.categories:empty().categories,debts:all.debts.map((d:any)=>({...d,tags:all.debt_tags.filter((t:any)=>t.debtId===d.id).map((t:any)=>all.tags.find((g:any)=>g.id===t.tagId)?.name).filter(Boolean)})),transactions:all.transactions,notes:all.notes,reminders:all.reminders,filters:all.saved_filters.map((f:any)=>({...f,value:JSON.parse(f.value)}))};return {state:s,user:u};}
function rows(s:State){const tags=[...new Set(s.debts.flatMap(d=>d.tags))].map(name=>({id:name,name}));return {people:s.people,categories:s.categories,debts:s.debts.map(({tags,...d})=>d),transactions:s.transactions,notes:s.notes,tags,debt_tags:s.debts.flatMap(d=>[...new Set(d.tags)].map(tag=>({debtId:d.id,tagId:tag}))),reminders:s.reminders,saved_filters:s.filters.map(f=>({...f,value:JSON.stringify(f.value)}))};}
export async function write(user:string,revision:number,old:State,next:State){validate(next);const nonce=uid();const guard='EXISTS (SELECT 1 FROM users WHERE id=? AND nonce=?)';const statements=[db().prepare('UPDATE users SET revision=revision+1,nonce=? WHERE id=? AND revision=?').bind(nonce,user,revision)];const before:any=rows(old),after:any=rows(next);for(const table of tables){const keys=table==='debt_tags'?['debtId','tagId']:['id'];const identity=(r:any)=>JSON.stringify(keys.map(k=>r[k]));const previous=new Map(before[table].map((r:any)=>[identity(r),r]));const current=new Map(after[table].map((r:any)=>[identity(r),r]));for(const [key,row] of previous as Map<string,any>)if(!current.has(key))statements.push(db().prepare(`DELETE FROM ${table} WHERE user_id=? AND ${keys.map(k=>snake(k)+'=?').join(' AND ')} AND ${guard}`).bind(user,...keys.map(k=>row[k]),user,nonce));for(const row of after[table]){if(JSON.stringify(previous.get(identity(row)))===JSON.stringify(row))continue;const cols=Object.keys(row);statements.push(db().prepare(`INSERT INTO ${table} (user_id,${cols.map(snake).join(',')}) SELECT ${['?',...cols.map(()=>'?')].join(',')} WHERE ${guard} ON CONFLICT (user_id,${keys.map(snake).join(',')}) DO UPDATE SET ${cols.map(k=>`${snake(k)}=excluded.${snake(k)}`).join(',')}`).bind(user,...cols.map(k=>row[k]),user,nonce));}}const result=await db().batch(statements);if(!result[0].meta.changes)throw Error('Данные изменились на другом устройстве. Обновите экран и повторите действие.');return revision+1;}
